name: Tests

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: black linter
        uses: psf/black@stable
        with:
          options: "--check --diff --line-length 90"
